ALTER TABLE public.providers ADD COLUMN pending_quota_reset_at timestamptz;
UPDATE public.providers
SET quota_last_reset_at = DATE_TRUNC('minute', quota_last_reset_at)
WHERE quota_last_reset_at IS NOT NULL;

ALTER TABLE public.usage_counter_deltas
    ADD COLUMN provider_billing_type_at_usage text,
    ADD COLUMN quota_epoch_start_at_usage bigint,
    ADD COLUMN provider_dispatch_at_unix_secs bigint,
    ADD COLUMN provider_quota_cost_usd double precision,
    ADD COLUMN pricing_rule_version_at_usage text,
    ADD COLUMN provider_pricing_snapshot_at_usage jsonb,
    ADD COLUMN quota_delta_sequence bigint GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN quota_accounting_status text;
CREATE UNIQUE INDEX ix_usage_counter_deltas_quota_sequence
    ON public.usage_counter_deltas (quota_delta_sequence);

ALTER TABLE public.provider_quota_window_counters
    RENAME TO provider_quota_window_counters_legacy;
ALTER TABLE public.provider_quota_window_counters_legacy
    RENAME CONSTRAINT provider_quota_window_counters_pkey
    TO provider_quota_window_counters_legacy_pkey;
ALTER TABLE public.provider_quota_window_counters_legacy
    RENAME CONSTRAINT provider_quota_window_counters_provider_id_fkey
    TO provider_quota_window_counters_legacy_provider_id_fkey;

CREATE TABLE public.provider_quota_window_counters (
    provider_id text NOT NULL REFERENCES public.providers(id) ON DELETE CASCADE,
    duration_secs bigint NOT NULL,
    window_start timestamptz,
    quota_epoch_start timestamptz NOT NULL,
    rolling_start timestamptz NOT NULL,
    accounted_until timestamptz NOT NULL,
    used_usd double precision NOT NULL DEFAULT 0,
    status text NOT NULL DEFAULT 'rebuilding',
    rebuild_error text,
    updated_at timestamptz NOT NULL DEFAULT NOW(),
    PRIMARY KEY (provider_id, duration_secs)
);

CREATE TABLE public.provider_quota_usage_buckets (
    provider_id text NOT NULL REFERENCES public.providers(id) ON DELETE CASCADE,
    quota_epoch_start timestamptz NOT NULL,
    bucket_start timestamptz NOT NULL,
    used_usd double precision NOT NULL DEFAULT 0,
    updated_at timestamptz NOT NULL DEFAULT NOW(),
    PRIMARY KEY (provider_id, quota_epoch_start, bucket_start)
);
